### ISSUE TITLE
Incorrect test result view in Azure DevOps after upgrading MSTest to 2.2.4 and higher

### ISSUE THREAD

**Issue by mabadev** [microsoft/testfx#1026]
## Description
After I updated MSTest.Framework and MSTest.Adapter to 2.2.4 and higher, the test results in Azure DevOps are displayed incorrectly.
Each test interation is displayed in a new line. Before that, the interations were shown under a test case.

_For example:_ A Test with 2 iterations

**Before**: 
TestCase12
- Iteration1
- Iteration2 

**Currently**

- TestCase12
- TestCase12

This a screenshot for the test results on Azure DevOps
_For example:_ Test Case 1129
![image](https://user-images.githubusercontent.com/19928575/146782783-a8fecbbb-c424-4bc6-a28b-21cf6a5e3fe5.png)

-----------------
**TRX-File look like different**
After the upgrade, the trx file does not contain an `<InnerResults>` element

Hier is a screenshot fom trx-file
![image](https://user-images.githubusercontent.com/19928575/146784866-7cfd82de-4520-4fcc-9146-2943ba547976.png)

---------

I use VS 2019 16.11.6
I'm not sure if this is a bug or a new configuration. This is my test configuration: [Configure unit tests by using a .runsettings file](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019)

**Comment by Legoldos** [comment]
Hey, I think this issued I recently posted is related/same #1024

**Comment by DotNetWebAppDeveloper** [comment]
> Hey, I think this issued I recently posted is related/same #1024

I think the main problem is the same.
thanks for that

**Comment by nohwnd** [comment]
This is not a bug, mstest now reports data driven tests as single tests. This was done to bring parity to how xunit and nunit does it. 

@Haplois  There are few duplicates of this issue. Could you link them all to a single one, and post an update on when the work on AzDO will be finished, please? 

Also correct my statement above if I am wrong :)

**Comment by TroyWalshProf** [comment]
@nohwnd  
The ONLY reason I and many other engineers use MSTest is because of the seamless integration with Azure DevOps Test Hub.
If you cannot maintain this integration you are just undermining the project.

Here are my concerns:
1. The team broke this integration a year ago and it has yet to be addressed
2. The interesting (wrong) assertion that this is "not a bug"
3. The trx report format has fundamentally changed and that doesn't seem to justify a major or minor version bump
4. I know this project and the [Azure DevOps Visual Studio Test task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops) are separate projects, but this kind of thing has the stink of the bad old days of Microsoft. - AKA Microsoft cannot seem to even work with itself

As far as I can tell here are the related/duplicate issues:
- https://github.com/microsoft/testfx/issues/860
- https://github.com/microsoft/testfx/issues/955
- https://github.com/microsoft/testfx/issues/992
- https://github.com/microsoft/testfx/issues/1023
- https://github.com/microsoft/testfx/issues/1026
- https://github.com/microsoft/testfx/issues/1035

**Comment by DotNetWebAppDeveloper** [comment]
> Duly noted. Believe me, I am not happy about this either. We are looking into conditionally reverting this change until it is fixed in azdo.

hoping to resolve this obstacle or to find an alternative solution for it. Our project has suffered because of that.

**Comment by ChristoWolf** [comment]
> > This is not a bug, mstest now reports data driven tests as single tests. This was done to bring parity to how xunit and nunit does it.
> > @Haplois There are few duplicates of this issue. Could you link them all to a single one, and post an update on when the work on AzDO will be finished, please?
> > Also correct my statement above if I am wrong :)
> 
> Hello @nohwnd Can you please provide link for some kind of documentation where this new behavior is explained? I couldnt find anything in MSTEST release notes. I would like something to grasp on when I explain this new behavior to my team.

I would also like to know, as I did not find the related changes by glancing over `2.2.4`'s release notes and commits.

**Comment by nohwnd** [comment]
@Haplois @Evangelink  did you get any update from AzDo about the progress of the fix? I know we talked with them a while ago.

**Comment by Haplois** [comment]
@nohwnd We didn't get an update - I pinged them.

**Comment by Haplois** [comment]
They have a fix, and expect to ship it next sprint. I asked about exact date.

**Comment by Nidolai** [comment]
@Haplois Thanks for the update looking forward to it.

**Comment by charlesdwmorrison** [comment]
Getting the next sprint date would be great.
As far as I can see, this change significantly breaks all test harnesses which are heavily Data Driven. I.e., test harness which have many rows in Excel, Access, or a Database. Teams following that methodology may have 100 test cases in one spreadsheet, with differ data rows of the spreadsheet testing different features, all going through one test method.  While this is not ideal, a lot of teams/organizations perform testing.
If one of these rows fails, the entire test fails? That does really skew the results.

Related well-reasoned posts on this issue include:
https://developercommunity.visualstudio.com/t/vstest-test-publication-miscounts-test-cases-and-c/909375
https://developercommunity.visualstudio.com/t/tests-tab-on-build-results-page-shows-wrong-test-c/1385811

Looking forward to seeing what the fix is. If is necessary to bring MSTest.exe in line with NUnit and XUnit, there should be a command line flag to allow for backward compatibility with the old approach.

**Comment by Haplois** [comment]
I spoke with the product team again, the fix in release pipeline and will be deployed within this sprint (which will be ending on 12th of September). I couldn't get an exact date.

/cc @dogirala from the product team.

**Comment by charlesdwmorrison** [comment]
So when will milestone 2.3.0 be pushed out?

**Comment by Evangelink** [comment]
Hi @charlesdwmorrison! My mistake, I should not have put any milestone on this ticket, as far as we know, sprint ended on 12th of September and roll out is supposed to have happened (@dogirala could you confirm?).
 
If you have tested and you are still experiencing the issue, please let us know and we will ping Azure DevOps team.

**Comment by dogirala** [comment]
@Evangelink , @charlesdwmorrison I see the fix has been deployed but somehow it didn't reflect in microsoft which is strange. For microsoft org I still see old PTR task version which is 2.203.0, ideally it should be 2.210.0. I am checking with my team and concerned deployments team. Will let you know as soon as I find out something on this. 
<img width="613" alt="image" src="https://user-images.githubusercontent.com/100841140/191683704-a7444cdd-25ac-4c5d-979f-c963eac40992.png">
Other ex pipeline: 
![image](https://user-images.githubusercontent.com/100841140/191684497-dd97baa4-da86-4697-94bb-2adae3f1416d.png)

**Comment by dogirala** [comment]
Got to know that this is expected as the deployments are still not completely done and they are in progress. Could not get any ETA but hopefully it will be deployed by this week.

**Comment by dogirala** [comment]
The fix is deployed now. All deployments are completed

**Comment by Evangelink** [comment]
I will move forward and close this ticket. Please if anyone is still experiencing issue either comment below or create a new ticket and we will handle it.

**Comment by MattBussing** [comment]
I'm confused. I thought there would be a new version of MSTest released to fix this issue. I'm not seeing a new version on NuGet.org.

https://www.nuget.org/packages/MSTest.TestFramework/2.3.0-preview-20220810-02#versions-body-tab

**Comment by charlesdwmorrison** [comment]
I am still seeing the same test case count as I have been for the past two years. In the test shown in the screenshot below, there are 126 data driven tests (in the form of an Excel spreadsheet). But the test results are only showing 1 test.
Where would the data driven counts show up?

![image](https://user-images.githubusercontent.com/24964349/193668878-da2e19f1-c90b-4d59-8d32-6b29282e1ee2.png)

**Comment by ChristoWolf** [comment]
> I'm confused. I thought there would be a new version of MSTest released to fix this issue. I'm not seeing a new version on NuGet.org.
> 
> https://www.nuget.org/packages/MSTest.TestFramework/2.3.0-preview-20220810-02#versions-body-tab

I'm also a bit confused.
My understanding now is that the discussed fix from above is not a fix to MSTest but the test results view, i.e. that the new test results format will now be visualized similarly to before the MSTest test results format change, right?
How can I make use of this when using Azure DevOps Server (i.e. on-prem)?

**Comment by dogirala** [comment]
For on-prem I think you'll need to download the latest agent and configure it for the new changes to be included

**Comment by Evangelink** [comment]
Hey there! Sorry the messages weren't super clear. 

The issue raised in this ticket wasn't linked to a problem in MSTest per say but it was linked to some change of behavior in MSTest (it should not have been done in a patch version) that wasn't reflected on AzDo side. AzDo team updated the behavior on their side and we were waiting for it to be deployed (according to @dogirala it was done 2 days ago).

Regarding on-prem instances, @dogirala could you please let us know what's the process? 

@charlesdwmorrison Could you confirm that you are using non on-prem AzDo?

I will make some more manual tests to confirm issue is correctly fixed and will post my results here. In the meantime, I will reopen the ticket.

**Comment by charlesdwmorrison** [comment]
I believe that is correct, Our AzDo instance is hosted by Microsoft, but we have our own agent machines. So that is "not on prem."

**Comment by dogirala** [comment]
For on-prem instances, as per my knowledge you need to configure a new Agent in the AgentPool section of organization for the latest changes to pick up:

![image](https://user-images.githubusercontent.com/100841140/194834782-14df611a-e32d-4a75-8a65-6b1eb19e33c8.png)

![image](https://user-images.githubusercontent.com/100841140/194834868-cc688d27-2b0c-4b50-91d1-25acf48bc157.png)

**Comment by charlesdwmorrison** [comment]
OK. I upgraded to agent version 2.210.1. I do see some changes, but the donut is still showing 1 test case for 126 data driven test cases. We can even see in the log that there are 126 cases. 
Is there another place I could see the full test case count? Is there more info I can give you? 

![image](https://user-images.githubusercontent.com/24964349/194969640-be43ce88-5e96-4939-9645-2f7ef10adad5.png)

**Comment by dogirala** [comment]
Ohh looks like you need to update your MStest adapter version as well. What is the MStest adapter version you are using?

**Comment by charlesdwmorrison** [comment]
Hi, sorry I've been gone for a while. Was in the hospital.
We are using Visual Studio 2017. We are not using a Nuget Package for either MSTest.exe, We use the MSFramework.dll that is installed on our local harddrives. We are not using any TestAdapater. We are on .Net framework 4.52. I have tried several versions of the MSTest.TestFramework in combination with various versions of the MSTest.TestAdapter (for instance 2.2.10) .  And when I run it in the pipeline with the reccomended test agent I get an error about "test adapter not found."  So I have several questions:. 
1. Is there any hope for us using this setup?
2. If we stick with Visual Studio 2017 is there any Nuget Package combination that will allow us to get a correct DataDriven count?
3. What's the lowest version of Visual Studio and .Net framework that you have tested the data driven test functionality?
4. What's the easiest upgrade path? What is your recommended VS, .Net / adapter  combination?  What builds of all these assemblies have you tested with? 
Thanks and sorry the question is so broad.

**Comment by dogirala** [comment]
Hi, I feel TestPlatform team can answers these questions better. @nohwnd can you or someone from your team please help clarify the above queries. To give you context, we have recently made a bug fix to resolve the duplicate testcase names observed for unittests with Mstest Adapter version 2.2.4+, wherein heirarchical display for data driven test is replaced with flat structure. @charlesdwmorrison is still seeing heirarchical display and I think he is trying to move to flat structure.

**Comment by charlesdwmorrison** [comment]
Just to be clear, what I am looking for is some method for Azure Devops to give an accurate count of the test executed. Since our tests are data driven by an Excel spreadsheet, we are looking, in effect, for Azure DevOps to measure the number of data rows we pass through a test method. In the above screenshot, the doughnut, in our opinion, should not say "1", it should say three because we passed three different rows of Excel data through the test method. These are three different tests.

**Comment by charlesdwmorrison** [comment]
Any update on this issue? It seems to me that this was the topic of this particular bug fix. Did the fix fix the issue?

**Comment by Evangelink** [comment]
@dogirala Could we setup some meeting/call to discuss this? As far as I can see, the main difference is that up to 2.2.3 we (MSTest) were using `<InnerResults/>` for storing the instances of a parameterized test (e.g. `DataRow`) which was leading to some incorrect count. For example, assuming you have a test method with 3 datarows, you will see 4 items (`UnitTestResult`) in the  `.trx` file: 1 for the "test method" and 3 as children of the "test method".

Real example with MSTest 2.2.3:

```xml
<Results>
	<UnitTestResult executionId="7c368e52-7c43-4b1a-8696-e12d5003d061" testId="cffe872d-a94b-a72a-efd2-1fb9ec28c26b" testName="DataRowTestMethod" computerName="LAPTOP" duration="00:00:00.0034511" startTime="2022-11-08T15:25:40.9841452+01:00" endTime="2022-11-08T15:25:40.9899959+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="7c368e52-7c43-4b1a-8696-e12d5003d061" resultType="DataDrivenTest">
		<InnerResults>
			<UnitTestResult executionId="6deb9d3f-02f8-4592-a7ad-da2c307b48d8" parentExecutionId="7c368e52-7c43-4b1a-8696-e12d5003d061" testId="cffe872d-a94b-a72a-efd2-1fb9ec28c26b" testName="DataRowTestMethod (0)" computerName="LAPTOP" duration="00:00:00.0001003" startTime="2022-11-08T15:25:40.9841452+01:00" endTime="2022-11-08T15:25:40.9899959+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="6deb9d3f-02f8-4592-a7ad-da2c307b48d8" dataRowInfo="1" resultType="DataDrivenDataRow" />
			<UnitTestResult executionId="1b8b1f06-a581-40ad-b8fd-af918c42b9b8" parentExecutionId="7c368e52-7c43-4b1a-8696-e12d5003d061" testId="cffe872d-a94b-a72a-efd2-1fb9ec28c26b" testName="DataRowTestMethod (1)" computerName="LAPTOP" duration="00:00:00.0000113" startTime="2022-11-08T15:25:40.9841452+01:00" endTime="2022-11-08T15:25:40.9899959+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="1b8b1f06-a581-40ad-b8fd-af918c42b9b8" dataRowInfo="2" resultType="DataDrivenDataRow" />
			<UnitTestResult executionId="c9490162-9341-4c9c-9be8-b34528d4b793" parentExecutionId="7c368e52-7c43-4b1a-8696-e12d5003d061" testId="cffe872d-a94b-a72a-efd2-1fb9ec28c26b" testName="DataRowTestMethod (2)" computerName="LAPTOP" duration="00:00:00.0000042" startTime="2022-11-08T15:25:40.9841452+01:00" endTime="2022-11-08T15:25:40.9899959+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="c9490162-9341-4c9c-9be8-b34528d4b793" dataRowInfo="3" resultType="DataDrivenDataRow" />
		</InnerResults>
	</UnitTestResult>
</Results>
```

Real example with MSTest 2.2.4+:

```xml
<Results>
	<UnitTestResult executionId="61cba81d-ea31-49ba-90e2-392492ded38a" testId="fbcb88c4-070c-4e3c-a6fc-fac91aafc616" testName="DataRowTestMethod (1)" computerName="LAPTOP" duration="00:00:00.0000037" startTime="2022-11-08T15:22:22.6686938+01:00" endTime="2022-11-08T15:22:22.6688093+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="61cba81d-ea31-49ba-90e2-392492ded38a" />
    <UnitTestResult executionId="c953f320-0876-425b-9cef-1fa6a3fbfd2f" testId="face297a-edd7-48ce-9aaa-65a72fe2c332" testName="DataRowTestMethod (0)" computerName="LAPTOP" duration="00:00:00.0000577" startTime="2022-11-08T15:22:22.6647551+01:00" endTime="2022-11-08T15:22:22.6686331+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="c953f320-0876-425b-9cef-1fa6a3fbfd2f" />
    <UnitTestResult executionId="79730bea-94e1-42e5-81ee-544788341d60" testId="22390aeb-07a5-4cbe-bdcd-2fe6c90b72f7" testName="DataRowTestMethod (2)" computerName="LAPTOP" duration="00:00:00.0000034" startTime="2022-11-08T15:22:22.6688280+01:00" endTime="2022-11-08T15:22:22.6690112+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="79730bea-94e1-42e5-81ee-544788341d60" />
</Results>
```

What would be interesting, is to understand how the grouping and count is done. I would expect that the `className` and `name` fields of the `TestDefinitions/UnitTest/TestMethod` nodes are used.

I am not sure how things are working on AzDo side so I cannot really tell if there is something unexpected on MSTest side or if issue is on AzDo side.

**Comment by charlesdwmorrison** [comment]
I am good anytime for a meeting.  What meeting platform would we use? Teams?

**Comment by Evangelink** [comment]
@charlesdwmorrison I will start by having a first call with @dogirala to sync on how things are working and what can be (or not) changed. If there are some floating point I will setup another meeting between the 3 of us and if things look ok, I will post back results of our discussion here.

**Comment by Evangelink** [comment]
Hey there. Thanks for bearing with us. We did more investigation with @dogirala and here are the results.

# Code example 

When running the tests for the following code:

```csharp
namespace MSTestProject
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
        }

        [DataRow(0)]
        [DataRow(1)]
        [DataRow(2)]
        [TestMethod]
        public void DataRowTestMethod(int i)
        {
        }
    }
}
```

# MSTest up to `2.2.3` (included)

## Result file (.trx)

The test result file (`.trx`) would look like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<TestRun id="89196f25-1585-46cb-9429-10e74cc201f4" name="currentUser@MyMachine 2022-11-08 15:25:41" runUser="currentUser" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2022-11-08T15:25:41.2734026+01:00" queuing="2022-11-08T15:25:41.2734030+01:00" start="2022-11-08T15:25:39.4674650+01:00" finish="2022-11-08T15:25:41.2866232+01:00" />
  <TestSettings name="default" id="a8af139d-1d5f-4b27-a369-5c0ee9dcc696">
    <Deployment runDeploymentRoot="currentUser_MyMachine_2022-11-08_15_25_41" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="6c135de3-73eb-4cbe-8f39-337340a6d650" testId="12713494-ea68-505c-1ae3-a995253433bd" testName="TestMethod1" computerName="MyMachine" duration="00:00:00.0077905" startTime="2022-11-08T15:25:40.8935789+01:00" endTime="2022-11-08T15:25:40.9730048+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="6c135de3-73eb-4cbe-8f39-337340a6d650" />
    <UnitTestResult executionId="7c368e52-7c43-4b1a-8696-e12d5003d061" testId="cffe872d-a94b-a72a-efd2-1fb9ec28c26b" testName="DataRowTestMethod" computerName="MyMachine" duration="00:00:00.0034511" startTime="2022-11-08T15:25:40.9841452+01:00" endTime="2022-11-08T15:25:40.9899959+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="7c368e52-7c43-4b1a-8696-e12d5003d061" resultType="DataDrivenTest">
      <InnerResults>
        <UnitTestResult executionId="6deb9d3f-02f8-4592-a7ad-da2c307b48d8" parentExecutionId="7c368e52-7c43-4b1a-8696-e12d5003d061" testId="cffe872d-a94b-a72a-efd2-1fb9ec28c26b" testName="DataRowTestMethod (0)" computerName="MyMachine" duration="00:00:00.0001003" startTime="2022-11-08T15:25:40.9841452+01:00" endTime="2022-11-08T15:25:40.9899959+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="6deb9d3f-02f8-4592-a7ad-da2c307b48d8" dataRowInfo="1" resultType="DataDrivenDataRow" />
        <UnitTestResult executionId="1b8b1f06-a581-40ad-b8fd-af918c42b9b8" parentExecutionId="7c368e52-7c43-4b1a-8696-e12d5003d061" testId="cffe872d-a94b-a72a-efd2-1fb9ec28c26b" testName="DataRowTestMethod (1)" computerName="MyMachine" duration="00:00:00.0000113" startTime="2022-11-08T15:25:40.9841452+01:00" endTime="2022-11-08T15:25:40.9899959+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="1b8b1f06-a581-40ad-b8fd-af918c42b9b8" dataRowInfo="2" resultType="DataDrivenDataRow" />
        <UnitTestResult executionId="c9490162-9341-4c9c-9be8-b34528d4b793" parentExecutionId="7c368e52-7c43-4b1a-8696-e12d5003d061" testId="cffe872d-a94b-a72a-efd2-1fb9ec28c26b" testName="DataRowTestMethod (2)" computerName="MyMachine" duration="00:00:00.0000042" startTime="2022-11-08T15:25:40.9841452+01:00" endTime="2022-11-08T15:25:40.9899959+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="c9490162-9341-4c9c-9be8-b34528d4b793" dataRowInfo="3" resultType="DataDrivenDataRow" />
      </InnerResults>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="TestMethod1" storage="c:\src\mstest-playground\mstestproject\mstestproject\bin\debug\net6.0\mstestproject.dll" id="12713494-ea68-505c-1ae3-a995253433bd">
      <Execution id="6c135de3-73eb-4cbe-8f39-337340a6d650" />
      <TestMethod codeBase="C:\src\mstest-playground\MSTestProject\MSTestProject\bin\Debug\net6.0\MSTestProject.dll" adapterTypeName="executor://mstestadapter/v2" className="MSTestProject.UnitTest1" name="TestMethod1" />
    </UnitTest>
    <UnitTest name="DataRowTestMethod" storage="c:\src\mstest-playground\mstestproject\mstestproject\bin\debug\net6.0\mstestproject.dll" id="cffe872d-a94b-a72a-efd2-1fb9ec28c26b">
      <Execution id="7c368e52-7c43-4b1a-8696-e12d5003d061" />
      <TestMethod codeBase="C:\src\mstest-playground\MSTestProject\MSTestProject\bin\Debug\net6.0\MSTestProject.dll" adapterTypeName="executor://mstestadapter/v2" className="MSTestProject.UnitTest1" name="DataRowTestMethod" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="12713494-ea68-505c-1ae3-a995253433bd" executionId="6c135de3-73eb-4cbe-8f39-337340a6d650" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="cffe872d-a94b-a72a-efd2-1fb9ec28c26b" executionId="7c368e52-7c43-4b1a-8696-e12d5003d061" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Completed">
    <Counters total="5" executed="5" passed="5" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
</TestRun>
```

What's important to note is:

- the total number of tests is **5** and not **4** as we would expect.
- the data row entries are not considered as individual tests but are grouped as `InnerResults` of the test method (they have the same test ID)
- the `TestDefinitions` only contains **2** entries

## Azure DevOps

Azure DevOps is parsing the trx file and using the results to populate their UI. For the previous trx file, display will be:

- `2/2` reported for the number of tests because they are reading the `TestDefinitions` entries of the trx.
- The datarow items (`DataRowTestMethod (0)`,  `DataRowTestMethod (1)`, `DataRowTestMethod (2)`) grouped under the one item named `DataRowTestMethod` because they are using the grouping provided in `UnitTestResult` of the trx.
- One extra element for `TestMethod1`

# MSTest from `2.2.4` (included)

## Result file (.trx)

The test result file (`.trx`) would look like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<TestRun id="f3a5ab2c-96f6-4c7f-a5c7-6f239db27664" name="currentUser@MyMachine 2022-11-08 15:22:22" runUser="currentUser" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2022-11-08T15:22:22.8553679+01:00" queuing="2022-11-08T15:22:22.8553683+01:00" start="2022-11-08T15:22:21.9392535+01:00" finish="2022-11-08T15:22:22.8715965+01:00" />
  <TestSettings name="default" id="d505dfd8-9081-4ad5-b030-af6556d675c2">
    <Deployment runDeploymentRoot="currentUser_MyMachine_2022-11-08_15_22_22" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="61cba81d-ea31-49ba-90e2-392492ded38a" testId="fbcb88c4-070c-4e3c-a6fc-fac91aafc616" testName="DataRowTestMethod (1)" computerName="MyMachine" duration="00:00:00.0000037" startTime="2022-11-08T15:22:22.6686938+01:00" endTime="2022-11-08T15:22:22.6688093+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="61cba81d-ea31-49ba-90e2-392492ded38a" />
    <UnitTestResult executionId="c953f320-0876-425b-9cef-1fa6a3fbfd2f" testId="face297a-edd7-48ce-9aaa-65a72fe2c332" testName="DataRowTestMethod (0)" computerName="MyMachine" duration="00:00:00.0000577" startTime="2022-11-08T15:22:22.6647551+01:00" endTime="2022-11-08T15:22:22.6686331+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="c953f320-0876-425b-9cef-1fa6a3fbfd2f" />
    <UnitTestResult executionId="79730bea-94e1-42e5-81ee-544788341d60" testId="22390aeb-07a5-4cbe-bdcd-2fe6c90b72f7" testName="DataRowTestMethod (2)" computerName="MyMachine" duration="00:00:00.0000034" startTime="2022-11-08T15:22:22.6688280+01:00" endTime="2022-11-08T15:22:22.6690112+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="79730bea-94e1-42e5-81ee-544788341d60" />
    <UnitTestResult executionId="d6e08bfa-b602-497a-8477-3d0711620467" testId="6349b831-af4e-4046-87c2-ec8e3ecffc93" testName="TestMethod1" computerName="MyMachine" duration="00:00:00.0031628" startTime="2022-11-08T15:22:22.6412291+01:00" endTime="2022-11-08T15:22:22.6584147+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="d6e08bfa-b602-497a-8477-3d0711620467" />
  </Results>
  <TestDefinitions>
    <UnitTest name="TestMethod1" storage="c:\src\mstest-playground\mstestproject\mstestproject\bin\debug\net6.0\mstestproject.dll" id="6349b831-af4e-4046-87c2-ec8e3ecffc93">
      <Execution id="d6e08bfa-b602-497a-8477-3d0711620467" />
      <TestMethod codeBase="C:\src\mstest-playground\MSTestProject\MSTestProject\bin\Debug\net6.0\MSTestProject.dll" adapterTypeName="executor://mstestadapter/v2" className="MSTestProject.UnitTest1" name="TestMethod1" />
    </UnitTest>
    <UnitTest name="DataRowTestMethod (1)" storage="c:\src\mstest-playground\mstestproject\mstestproject\bin\debug\net6.0\mstestproject.dll" id="fbcb88c4-070c-4e3c-a6fc-fac91aafc616">
      <Execution id="61cba81d-ea31-49ba-90e2-392492ded38a" />
      <TestMethod codeBase="C:\src\mstest-playground\MSTestProject\MSTestProject\bin\Debug\net6.0\MSTestProject.dll" adapterTypeName="executor://mstestadapter/v2" className="MSTestProject.UnitTest1" name="DataRowTestMethod" />
    </UnitTest>
    <UnitTest name="DataRowTestMethod (0)" storage="c:\src\mstest-playground\mstestproject\mstestproject\bin\debug\net6.0\mstestproject.dll" id="face297a-edd7-48ce-9aaa-65a72fe2c332">
      <Execution id="c953f320-0876-425b-9cef-1fa6a3fbfd2f" />
      <TestMethod codeBase="C:\src\mstest-playground\MSTestProject\MSTestProject\bin\Debug\net6.0\MSTestProject.dll" adapterTypeName="executor://mstestadapter/v2" className="MSTestProject.UnitTest1" name="DataRowTestMethod" />
    </UnitTest>
    <UnitTest name="DataRowTestMethod (2)" storage="c:\src\mstest-playground\mstestproject\mstestproject\bin\debug\net6.0\mstestproject.dll" id="22390aeb-07a5-4cbe-bdcd-2fe6c90b72f7">
      <Execution id="79730bea-94e1-42e5-81ee-544788341d60" />
      <TestMethod codeBase="C:\src\mstest-playground\MSTestProject\MSTestProject\bin\Debug\net6.0\MSTestProject.dll" adapterTypeName="executor://mstestadapter/v2" className="MSTestProject.UnitTest1" name="DataRowTestMethod" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="fbcb88c4-070c-4e3c-a6fc-fac91aafc616" executionId="61cba81d-ea31-49ba-90e2-392492ded38a" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="face297a-edd7-48ce-9aaa-65a72fe2c332" executionId="c953f320-0876-425b-9cef-1fa6a3fbfd2f" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="22390aeb-07a5-4cbe-bdcd-2fe6c90b72f7" executionId="79730bea-94e1-42e5-81ee-544788341d60" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="6349b831-af4e-4046-87c2-ec8e3ecffc93" executionId="d6e08bfa-b602-497a-8477-3d0711620467" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Completed">
    <Counters total="4" executed="4" passed="4" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
</TestRun>
```

What's important to note is:

- the total number of tests is **4**.
- the data row entries are flatten and have different test IDs.
- the `TestDefinitions` contains **4** entries

## Azure DevOps

Azure DevOps is parsing the trx file and using the results to populate their UI. For the previous trx file, display will be:

- `4/4` reported for the number of tests because they are reading the `TestDefinitions` entries of the trx.
- All datarow items are displayed flat (`DataRowTestMethod (0)`,  `DataRowTestMethod (1)`, `DataRowTestMethod (2)`) at the same indent level as `TestMethod1`.

# Reasoning for the change in 2.2.4

This change was done to overcome some issues on MSTest (e.g. if datarows are displayed as children they cannot have a different test ID and so are not expanded in Visual Studio - leading to impossibility to run/debug only 1 case) and also to have a better parity with results of `NUnit` and `xUnit` test frameworks. 

# What's next

I am going to start a discussion with AzDo team to improve the UX by allowing some grouping by test while keeping the test count, test filter and other functionalities working properly.

**Comment by Evangelink** [comment]
> Hi, sorry I've been gone for a while. Was in the hospital. We are using Visual Studio 2017. Typically we do not using a Nuget Package for either MSTest.exe, We use the MSFramework.dll that is installed on our local hard drives. We typically are not using any TestAdapater. We are typically on .Net framework 4.52. I have tried several versions of the MSTest.TestFramework in combination with various versions of the MSTest.TestAdapter (for instance 2.2.10) . And when I run it in the pipeline with the reccomended test agent I get an error about "test adapter not found." So I have several questions:. 1.. If we stick with Visual Studio 2017 is there any Nuget Package combination that will allow us to get a correct DataDriven count? 2. What's the lowest version of Visual Studio and .Net framework that you have tested the data driven test functionality?
> 
> I did upgrade one of our test solutions to .Net 4.6 and I got the following result:
> 
> ![image](https://user-images.githubusercontent.com/24964349/197942443-70f94147-3698-4cdf-b2fb-cf1ee648ba16.png)

@charlesdwmorrison We have run some tests and we are wondering if there might be some configuration issue on your end because you are saying that you are using the agent `2.210` and MSTest `2.2.10` but your screenshot is showing some grouping which should not happen in this combination. Could you double check the versions? Ensure MSTest adapter and framework are using the same version. Could you also confirm that you are not using `[assembly: TestDataSourceDiscovery(TestDataSourceDiscoveryOption.DuringExecution)]`?

**Comment by charlesdwmorrison** [comment]
Just want to mention I am working on making sure I am giving you the correct information.
We have some very legacy elements in our system, including the fact that our ADO is hooked up to a Team Foundation server as the source repository. I am making some changes to ensure that I am giving you the right info.

**Comment by Evangelink** [comment]
I don't know what's possible on your end but if you could create a simple MSTest project outside of any existing solution and pipeline and do a pipeline just building, testing publishing results of this project could help checking you have the same behavior by eliminating influence of some other factors.

**Comment by charlesdwmorrison** [comment]
P.S. It also could be that our TFS server is just not configured correctly. I would guess that its configuration has not been revisited since ~2015. It seems like it just doesn't deliver the source code developed in VS 2022 to the Azure DevOps agent correctly. The easy solution is to move to GitHub. Will try to help the team do it.

**Comment by Evangelink** [comment]
@charlesdwmorrison Awesome news! Thanks for keeping us posted with your results.

I will keep this ticket open as I do think there is some UX improvement that needs to be done on AzDo and will discuss with the their team how we can proceed.

**Comment by charlesdwmorrison** [comment]
Regarding Needed UX improvements here are some observations.
Things are not working when executing from a Test Plan. 
What I am seeing that with the latest MSTest.TestAdapter, and the latest MsTest.TestFramework data driven tests ARE being reported correctly when executed from a "build" pipeline or a release pipeline.
However, the counting is NOT working correctly when the same tests are executed from a Test Plan.
The test Plan is another layer on top of the build and release pipelines. My guess is there is some event that is not being passed from the Test Plan, back to the release pipeline.

Steps to Repro
----------------
1. Create build and release pipelines according to this article: https://dev.azure.com/JHA-5/EPSQA/_releaseDefinition?definitionId=62&_a=environments-editor-preview
2. Create a new test plan.
3. Create a new test case in the test plan. Grab the test case ID.
4. From the Visual Studio Test solution, associate a VS test case to the new test plan using the test case ID.
5.       (In ADO, if you now open the test case, and move to the tab "Associated Automation" you will see your test assembly.) 
6. Run the test case from the test plan. Choose "Run with Options". The release pipeline you created in step 1 should show up.  Note that the release pipeline property "Chose tests using" needs to be set to "Test Run" to get it to work from the test plan.
7. When the test finishes, look at the run  summary . We can also go back the release log .

Bug==> Both the summary and the release log should enumerate the data driven results. But They do not. They just enumerate the number of test methods executed.
     In addition, there are two more problems:
    a. The release summary doughnut does not show any color, it is still gray.
    b. If we go back to the text plan from which we executed the test, the test we executed still shows "In Progress" even though both the test agent and the pipeline indicate that the test is complete.

Additional Information/Tests
-------------------------
It seems like an event or bit of data indicating the number of data driven tests  is not passed from the test plan to the release pipeline.
For a further test, we can reuse the pipeline by changing the "Select Tests Using" property from "Test Run" to "Test Assemblies." We can filter the tests by putting something like "TestCategory=QA_Smoke" as the test filter. 
Now manually press "Create Release" on the release pipeline.
Result ==> We DO get the correct results of a data driven test.

Here are some screenshot illustrating what I am seeing when executing from a test plan.

![image](https://user-images.githubusercontent.com/24964349/202299146-5a84a18b-89a5-4650-898d-f0b9494b4f9f.png)

![image](https://user-images.githubusercontent.com/24964349/202299388-9b38899d-3d2e-48fe-a860-5df6aad97db4.png)

Here is the same pipeline, but where I have changed to "test assemblies" and put in a filter and executed the pipeline by pressing "Create Release:"

![image](https://user-images.githubusercontent.com/24964349/202299880-b4ef685f-7ca9-4034-be92-5e4b1236b205.png)

**Comment by Evangelink** [comment]
@dogirala What's the correct repository to track this issue? It doesn't seem to be related to MSTest.

**Comment by dogirala** [comment]
hello @Evangelink, @charlesdwmorrison. I was OOF last week. Will take a look at this today and get it tracked accordingly.

**Comment by charlesdwmorrison** [comment]
Any updates on this? My team relies heavily on running tests from test plans.

**Comment by dogirala** [comment]
@charlesdwmorrison @Evangelink  Sorry for the delay in response, I have gone through the issue, and it seems like this is a known issue [link](https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1954432/) that we have created bug a while ago where we observed incorrect associations being happening in visual studio. We have yet to figure out the right team that owns this. I will work upon this to triage this bug to the right team and to assign this discussion to them. Could you help me with the below queries just for my confirmation

  - Which version of the MS Test Adapter are you using is it 2.2.4+ ?
  -  While doing 'Associate to testcase' in visual studio, did you observe that if you do associate to one testcase in the data driven , all the the data driven rows will get automatically associated to that testcase? Like in the below screenshot
  
![image](https://user-images.githubusercontent.com/100841140/205826556-ff90d9b9-c669-4d9c-a95f-fba4b12d4174.png)

Here I have tried to associate data driven test with input 10 and automatically 20 and 30 are also associated.

**Comment by charlesdwmorrison** [comment]
1. I am using version 2.2.10 of the test adapter. (see screenshot below).
2. Yes, when I use Test Decorations to make data rows above my test method as you show in the above screen shot, then, yes, if I associate one of the datarows with a test case, then the other datarows are also automatically associated to that test case as well.  I can see how that might be problematic.

However I did want to mention one additional point: Our data-driven test case are in Excel. We don't use a simple test Decorations to data-drive our test cases. we use a datasource like the following to connect to an Excel datasheet

[DataSource("System.Data.OleDb", "Provider=Microsoft.ACE.OLEDB.12.0;" +
                                         "Data Source=|DataDirectory|\\Data\\TestInputData\\AccountManagement\\GetAccount.xlsx;" +
                                         "Persist Security Info=False;Extended Properties='Excel 12.0 Xml;HDR=YES'", "QA_Smoke$", DataAccessMethod.Sequential)]

With our, classic, approach of adding test data to a test method (using an Excel datasheet), there is no opportunity to associate only one of the data rows to a test case ID. The only thing to do is to associate the entire test method to a test case ID.
The same would be true, I think, if our test data were kept in SQL Server or Access. The Test Manager does not have an opportunity to inspect data in Excel, SQL Server, or Access,  and has no ability to break out these individual rows.

If there WERE an opportunity to associate only certain rows of  Excel data to a test case, I can certainly see how that would be an advantage to a testing effort. However, with the approach of using the Microsoft.ACE.OLEDB test adapter, I don't think there is any opportunity to do this.

The bug, it seems to me, is in how Azure DevOps counts the test case execution. However, I don't know the inner workings of these assemblies. 

Here is a screenshot of the MSTest.TestAdapters I am using:
![image](https://user-images.githubusercontent.com/24964349/206533555-fc656f07-8b39-4ba3-b59b-86ed4809ad87.png)

**Comment by charlesdwmorrison** [comment]
I forgot to mention that the link you posted above ([link](https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1954432/)) seems to go to an MS internal ADO. Do you have any public information on that issue?

**Comment by Evangelink** [comment]
@dogirala Yeah it'd be good if you had some public ticket tool where community could follow things up. It seems a little weird to have to track AzDo test issues through vstest or testfx repositories.

**Comment by charlesdwmorrison** [comment]
Update and **Question for Microsoft**
Is the following a supported way to access an Excel data source from a unit test:

[DataSource("System.Data.OleDb", "Provider=Microsoft.ACE.OLEDB.12.0;" +
"Data Source=|DataDirectory|\Data\TestInputData\AccountManagement\GetAccount.xlsx;" +
"Persist Security Info=False;Extended Properties='Excel 12.0 Xml;HDR=YES'", "QA_Smoke$", DataAccessMethod.Sequential)]

I ask this because:
1. I can find no official Microsoft references to this approach to accessing an Excel datasource. In official docs, I see the [TestContext ](https://learn.microsoft.com/en-us/visualstudio/test/how-to-create-a-data-driven-unit-test?source=recommendations&view=vs-2022)being advocated, or a [config file](https://learn.microsoft.com/en-us/visualstudio/test/walkthrough-using-a-configuration-file-to-define-a-data-source?view=vs-2022).
2. There is at least one blog which hints that paths that are too long interfere with test case counting. See [here](https://developercommunity.visualstudio.com/t/not-all-run-tests-are-published-in-test-run-summar/1107439 ).
3. I have been able to get our test solutions to somewhat work from Test Plans with shorter data access paths such as:

[TestMethod]
    [DataSource("System.Data.Odbc", @"Dsn=Excel Files;dbq=c:\feedback\exceldata\serialnos.xlsx", "Sheet1$", DataAccessMethod.Random)] 

**Is the OleDB approach that I show above deprecated?**

Thanks.

**Comment by Evangelink** [comment]
@charlesdwmorrison I know that's far from ideal answer but I also cannot find much document about it and I know the feature only works for netfx at the moment so I will need some time to investigate the code and past versions to see if there was some change impacting you.

Regarding, AzDo related issues (test plan, test view...) are not under my umbrella so there is nothing much I can do except pinging the related team (which I do).

**Comment by charlesdwmorrison** [comment]
Is there a link to a github or ms dev forum where I could post the issue of data access to Excel in unit tests more directly?

**Comment by Evangelink** [comment]
You can try through https://developercommunity.visualstudio.com/. For the GitHub repo, @dogirala please let us know.

**Comment by dogirala** [comment]
hi @Evangelink, @charlesdwmorrison I am on top of this, please expect an update by tomorrow. From what I checked the issue is not with the testplans rather it is the 'Associate to testcase' functionality of visual studio. I don't have much info regarding the owing team and the public ticket that would reach to them, but I am working on this.

**Comment by Evangelink** [comment]
If that's Test Explorer side, we have some contacts (cc @AbhitejJohn)

**Comment by dogirala** [comment]
@AbhitejJohn could you please take a look at the bug and clarify who should be the right team that owns that workflow? I was having a discussion with couple of folks from test plans and there seems to be some confusion around it.

**Comment by dogirala** [comment]
Had checked with @AbhitejJohn and got the details on the owning team. The bug is assigned Automation Testing team and will be prioritized in the coming sprints. Will follow-up with the team regarding public ticket on the same. Will update on it here. Thanks

**Comment by Evangelink** [comment]
Closing this ticket as there is nothing left on MSTest side.

**Comment by charlesdwmorrison** [comment]
Could we get a URL to  where the Automation Testing team is tracking this or providing public updates?

**Comment by Evangelink** [comment]
Hey all,

I have open a ticket on Dev Community https://developercommunity.visualstudio.com/t/Incorrect-test-result-view-in-Azure-DevO/10359804?q=Incorrect+test+result+view for you all to track. Please do upvote the ticket.

**Comment by dogirala** [comment]
Hello Amaury,

Thanks for the email. Adapting Tcm with Test Adapter latest versions and incorporate any improvements is one of the priority features for us in this semester.

Right now, I am working on going through the older customer tickets we have received regarding the issue customers are facing due to, parity mismatch between the Test Adapter changes and how TCM as a service is consuming the trx file.

Please give me 1-2 days to go over the older tickets and the suggestions you have shared, to come up with a short plan to address the problem and improve the overall Ux for the customers. Below are the key things we are targeting

    - Fix all current issues due to data driven changes in latest Test Adapter versions and how trx is file parsed and consumed.
    - Check feasibility and Incorporate the suggestions you have shared to improve the overall UI/UX to the customer.
     - Come up with a means to have this parity for future as well, so that if there are any changes done in Test Adapter, corresponding adaptive changes are done in TCM as well.

We would require your support in delivering this, would reach out to the test platform team in 1-2 days to discuss more on this. Appreciate your support.

Thanks and regards,
Prabhakar
________________________________

**Comment by dogirala** [comment]
@charlesdwmorrison Just sharing an update on the issue you mentioned above. We have merged a fix for that issue. It required a two-part fix, one on the visual studio application and the other on the azure devops. The fix on the visual studio would be available from VS 17.7 Preview 3 version. However, the fix would be applicable for all new associations, so the associations need to be done from visual studio.

**Comment by charlesdwmorrison** [comment]
Thanks. We are familiar with the association of test case process. Not our favorite thing, but we will check it out. Is this the download point for a VS Preview that contains the fix: [https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview) (I see that this says  VS 17.8).

**Comment by dogirala** [comment]
Hi yes, this is the page. Right now it says the newest is 17.8 preview 2, the next version should have the fix.

**Comment by b3go** [comment]
> Hi yes, this is the page. Right now it says the newest is 17.8 preview 2, the next version should have the fix. Also, just to add, the change is under a featureflag **TestExecution.ModifiedFqnAssociation**, for hosted ado, I am in the process of enabling this shortly. For onprem, please register and enable this FF in config db. Please reach out to us via CSS for any further assistance on the same

@dogirala using mstest adapter and framework 3.2.0, azure devops server 2022 and self hosted agents with VS 2022 17.8.6. I added this row in tbl_RegistryItems in the tfs_configuration db and restarted the IIS: 
```
PartitionId	ParentPath	ChildItem	RegValue
1	#\FeatureAvailability\Entries\TestExecution.ModifiedFqnAssociation\	AvailabilityState\	1
```

Running tests with a parallel strategy doesn't work. Only the first DataRow is executed, the others are not mentioned (neither .trx, nor Test Result Window:
![image](https://github.com/microsoft/testfx/assets/52070186/d17d05a6-5c2f-4674-8cef-ae266cf2e8b5)

However running on one agent works, as all DataRows are properly executed and also displayed in Test Resuts:
![image](https://github.com/microsoft/testfx/assets/52070186/c889ce51-80db-4681-9f60-d12440b0422d)
![image](https://github.com/microsoft/testfx/assets/52070186/c0f2e4bd-075a-4167-be81-c729f7b1de59)

Unfortunately running on one agent is not possible in this case. These are "unstable" tests that have to rerun if failed (some static cache issues in big legacy app). Which results in this error https://github.com/microsoft/azure-pipelines-tasks/issues/16187 if executed without batch/slicing

**Comment by dogirala** [comment]
hi @b3go, yes, we've identified this bug and we've fixed this now. Can you share what is the version of Vstest task you are using?. And can you update the Visual studio test task version and give this a try and let me know if you are facing this issue?

**Comment by b3go** [comment]
> hi @b3go, yes, we've identified this bug and we've fixed this now. Can you share what is the version of Vstest task you are using?. And can you update the Visual studio test task version and give this a try and let me know if you are facing this issue?

Hi @dogirala!
My current task version is 2.224.0 which is the version that get's shipped with the server. 

I wanted to try an update using this documentation https://learn.microsoft.com/en-us/azure/devops/extend/develop/upload-tasks?view=azure-devops but I am unable to build the task in the azure-pipelines-tasks repo, as documented here https://github.com/microsoft/azure-pipelines-tasks/blob/63e9d5a7dc5981ee4d265c119541de8461bd0b20/docs/contribute.md#build-a-specific-task-recommended

Currently checked out is commit b7f22b03477ff0a692b30d32e7b75610260e4b8f
Running 
```ps
node make.js build --task VsTestV2
```
gives this Output:
```
Found package.json for VsTestV2 in Tasks folder C:\Users\UserName\source\repos\azure-pipelines-tasks\Tasks\VsTestV2\package.json
Node verion from @types/node in package.json is 16.11.39 returning 16
Found package.json for VsTestV2_Node20 in _generated folder C:\Users\UserName\source\repos\azure-pipelines-tasks\_generated\VsTestV2_Node20\package.json
Node verion from @types/node in package.json is 20.3.1 returning 20
Found package.json for VsTestV2 in Tasks folder C:\Users\UserName\source\repos\azure-pipelines-tasks\Tasks\VsTestV2\package.json
Found package.json for VsTestV2_Node20 in _generated folder C:\Users\UserName\source\repos\azure-pipelines-tasks\_generated\VsTestV2_Node20\package.json
Node verion from @types/node in package.json is 20.3.1 returning 20

> node -v
skipping node install for tests since correct version is running
node tool:
C:\PROGRAM FILES\NODEJS\NODE.EXE
------------------------------------------------------------
Building task VsTestV2_Node20 using Node.js 20
------------------------------------------------------------
Found generated task: VsTestV2_Node20
Remove existing outDir: C:\Users\UserName\source\repos\azure-pipelines-tasks\_build\Tasks\VsTestV2_Node20

> getting task externals
Downloading file: https://testselectorv2.blob.core.windows.net/testselector/7841796/TestSelector.zip
Could not use "nc", falling back to slower node.js method for sync requests.
C:\Users\UserName\source\repos\azure-pipelines-tasks\node_modules\sync-request\index.js:77
    throw new Error(res.stderr.toString());
    ^

Error
    at doRequestWith (C:\Users\UserName\source\repos\azure-pipelines-tasks\node_modules\sync-request\index.js:77:11)
    at doRequest (C:\Users\UserName\source\repos\azure-pipelines-tasks\node_modules\sync-request\index.js:20:10)
    at downloadFile (C:\Users\UserName\source\repos\azure-pipelines-tasks\make-util.js:412:22)
    at downloadArchive (C:\Users\UserName\source\repos\azure-pipelines-tasks\make-util.js:460:27)
    at C:\Users\UserName\source\repos\azure-pipelines-tasks\make-util.js:672:33
    at Array.forEach (<anonymous>)
    at getExternals (C:\Users\UserName\source\repos\azure-pipelines-tasks\make-util.js:667:25)
    at buildTask (C:\Users\UserName\source\repos\azure-pipelines-tasks\make.js:318:9)
    at C:\Users\UserName\source\repos\azure-pipelines-tasks\make-util.js:1869:26
    at C:\Users\UserName\source\repos\azure-pipelines-tasks\make.js:221:44

Node.js v20.3.1
```
I found this workaround [15596](https://github.com/microsoft/azure-pipelines-tasks/issues/15596#issuecomment-995205846). But now I get: 
```
Downloading file: https://github.com/Microsoft/vswhere/releases/download/1.0.62/vswhere.exe
C:\Users\UserName\source\repos\azure-pipelines-tasks\node_modules\sync-request\index.js:77
    throw new Error(res.stderr.toString());
    ^

Error: C:\Users\UserName\source\repos\azure-pipelines-tasks\node_modules\http-basic\index.js:100
      if (options.followRedirects && isRedirect(res.statusCode)) {
                                                    ^

TypeError: Cannot read properties of undefined (reading 'statusCode')
    at C:\Users\UserName\source\repos\azure-pipelines-tasks\node_modules\http-basic\index.js:100:53
    at C:\Users\UserName\source\repos\azure-pipelines-tasks\node_modules\http-basic\index.js:224:9
    at ClientRequest.<anonymous> (C:\Users\UserName\source\repos\azure-pipelines-tasks\node_modules\http-basic\index.js:251:5)
    at ClientRequest.emit (node:events:511:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:511:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.3.1

    at doRequestWith (C:\Users\UserName\source\repos\azure-pipelines-tasks\node_modules\sync-request\index.js:77:11)
    at doRequest (C:\Users\UserName\source\repos\azure-pipelines-tasks\node_modules\sync-request\index.js:20:10)
    at downloadFile (C:\Users\UserName\source\repos\azure-pipelines-tasks\make-util.js:412:22)
    at C:\Users\UserName\source\repos\azure-pipelines-tasks\make-util.js:709:30
    at Array.forEach (<anonymous>)
    at getExternals (C:\Users\UserName\source\repos\azure-pipelines-tasks\make-util.js:704:15)
    at buildTask (C:\Users\UserName\source\repos\azure-pipelines-tasks\make.js:318:9)
    at C:\Users\UserName\source\repos\azure-pipelines-tasks\make-util.js:1869:26
    at C:\Users\UserName\source\repos\azure-pipelines-tasks\make.js:221:44
    at Array.forEach (<anonymous>)

Node.js v20.3.1
```

I can download the file manually though. Any ideas?

Thanks in advance

**Comment by b3go** [comment]
Hi @dogirala, had some troubles building the task but I was finally able to get it working. I am now using VSTestV2 2.229.0 but still getting the same issue. With the parallel strategy the slicing of the test cases with DynamicData/DataRow doesn't seem to work. I still get only the first case.

I've found this in the documentation https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/vstest-v2?view=azure-pipelines#i-am-running-into-issues-when-running-data-driven-xunit-and-nunit-tests-with-some-of-the-task-options-are-there-known-limitations
As stated in vstest@2 it is not supported to distribute the tests on multiple different agents in xUnit and NUnit. Could it be that this is now also the same with MsTest because since 2.2.4 the test names are generated in the same way as in xUnit and NUnit?

**Comment by dogirala** [comment]
@b3go apologies for the delay, I see you are using 2.229.0, from what I checked the change we did went into 2.234.0, can you try with any version vstestv2 2.234.0 or more, the distributed scenario should work as expected, please let me know if you are still seeing this issue, I'll try to connect with you to debug it further

**Comment by dogirala** [comment]
@b3go  can you help me with couple of queries?
   - Are these mstest unittests that you are running?
   - What is the exact scenario in vstest you are running? Is it testassemblies + parallel strategy?
   - For DynamicData/DataRow, are you overriding the displayName method and setting a customer displayName? --> If yes, can you try generating it something like below?
   
      public string GetDisplayName(MethodInfo methodInfo, object[] data)
    {
        if (data != null)
        {
            var testParamString = new StringBuilder();
            testParamString.Append(methodInfo.Name);

            testParamString.Append(' (');
            var methodParameters = methodInfo.GetParameters();
            for (int i = 0; i < methodParameters.Length; i++)
            {
                testParamString.Append(data[i]);
                testParamString.Append(',');
            }
            testParamString.Length--;
            testParamString.Append(')');

            return testParamString.ToString();
        }

        return methodInfo.Name;
    }

**Comment by dogirala** [comment]
@b3go thanks for sharing the details, will check and get back shortly.

**Comment by b3go** [comment]
@dogirala Hi do you have any updates on this matter?

**Comment by dogirala** [comment]
Hi @b3go, apologies for the delay, I was out of office, the past couple of weeks, I am back to office this week, I will look into this and create a tracking item for this.

**Comment by catalin7mar** [comment]
@dogirala Hi! Do you have any updates? At my new company, I discovered that the following issue is still present, which is why we are still using TestAdapter 2.2.3. 

Here's the behavior we're observing (Agent Version 2.195.2):

We run our permission tests on a remote desktop using various test plans from Azure DevOps (Net 6).

![image](https://github.com/microsoft/testfx/assets/28535063/a7091c06-2eaf-4d4f-b5c9-e4e56594c772)
![image](https://github.com/microsoft/testfx/assets/28535063/e53d4a8a-c1ba-4ce1-9395-392e7bd7e2aa)

When running the tests on my local machine, the result of failed test cases is correct:
![image](https://github.com/microsoft/testfx/assets/28535063/47de6b60-ae52-4ca2-b986-88bda4a334c9)

However, when I create a release in Azure, the output is not correctly captured:
![image](https://github.com/microsoft/testfx/assets/28535063/e8243d0c-c1bd-471e-b615-f42622636826)

**Comment by dogirala** [comment]
Hi @catalin7mar, are you using ADO onprem server or hosted?

**Comment by catalin7mar** [comment]
@dogirala Hi! onprem

**Comment by dogirala** [comment]
@catalin7mar can you please register and turn on this FF --> **TestExecution.EnableParentChildForEmptyDataDrivenDynamicTests**

For registration, you can follow the below steps -

Execute the below on configuration DB, replace the {featureflagname} with the above highlighted

INSERT INTO tbl_RegistryItems (PartitionId, ParentPath, ChildItem, RegValue)

VALUES
 (1,'#\FeatureAvailability\Definitions\{FeatureFlagName}\', 'Description\', 'Flag for controlling enabling of association to testcase workflows with modified Fully Qualified Name'),
 (1,'#\FeatureAvailability\Definitions\{FeatureFlagName}\', 'Name\', '{FeatureFlagName}'),
 (1,'#\FeatureAvailability\Definitions\{FeatureFlagName}\', 'Owner\', '{Service}')
 
EXEC prc_SetRegistryValue 1, '#\FeatureAvailability\Entries\{FeatureFlagName}\AvailabilityState\', 1

Restart the IIS Web App for the Azure DevOps collection.

**Comment by b3go** [comment]
Hi @dogirala me again :D

how does **TestExecution.EnableParentChildForEmptyDataDrivenDynamicTests** add to **TestExecution.ModifiedFqnAssociation**? (btw I think you missed a `\` between Defintions/Entries and {FeatureFlagName})

Could be that I actually made a mistake enabling the Feature Flag, I only added the row manually

```
PartitionId	ParentPath	ChildItem	RegValue
1	#\FeatureAvailability\Entries\TestExecution.ModifiedFqnAssociation\	AvailabilityState\	1
```

So what I would do now is:

```sql
INSERT INTO tbl_RegistryItems (PartitionId, ParentPath, ChildItem, RegValue)

VALUES
(1,'#\FeatureAvailability\Definitions\TestExecution.ModifiedFqnAssociation', 'Description', 'Flag for controlling enabling of association to testcase workflows with modified Fully Qualified Name'),
(1,'#\FeatureAvailability\Definitions\TestExecution.ModifiedFqnAssociation', 'Name', 'TestExecution.ModifiedFqnAssociation'),
(1,'#\FeatureAvailability\Definitions\TestExecution.ModifiedFqnAssociation', 'Owner', '{Service}')

EXEC prc_SetRegistryValue 1, '#\FeatureAvailability\Entries\TestExecution.ModifiedFqnAssociation\AvailabilityState', 1
```

What would be the value for `{service}`?

Thanks!

**Comment by raghere** [comment]
@b3go  We have exactly the same problem. Could you please let us know if the FeatureFlag solution metioned above worked for you ? Thanks.

**Comment by b3go** [comment]
@raghere unfortunately I haven't got an answer to my last question. Therefore I decided to stick with my workaround, where I execute the test job in a matrix and distribute the tests based on TestCategories. It is a suboptimal solution which actually costs us a lot of execution time in our pipeline but I can't invest any more time into this.

**Comment by raghere** [comment]
@b3go Thank you for your response. It’s unfortunate that we’ll have to settle for either a workaround or version 2.2.3. :-(
