### ISSUE TITLE
MSTest v3 TestContext.Properties is marked as returns nullable

### ISSUE THREAD

**Issue by Mertsch** [microsoft/testfx#1376]
## Describe the bug
MSTest 3.0.0-preview-20221110-04
`TestContext.Properties` now returns `IDictionary?` which causes null ref warnings/errors everywhere.

## Expected behavior
`TestContext.Properties` returns `IDictionary` or even better `IDictionary<string, object>`

## Actual behavior
`TestContext.Properties` now returns `IDictionary?`
https://github.com/microsoft/testfx/blob/511544c9bdf9ab4cd2b108cd23f2fd0ea5732307/src/TestFramework/TestFramework.Extensions/TestContext.cs#L23

[AB#1675507](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1675507)

**Comment by Evangelink** [comment]
Hi @Mertsch, you are right, I incorrectly annotated some of the `TestContext` properties. I will review that and file a PR quickly.

**Comment by Evangelink** [comment]
Hi @Mertsch, I have published the new pre-release version if you are interested: https://github.com/microsoft/testfx/releases/tag/v3.0.0-preview-20221122-01

**Comment by Mertsch** [comment]
@Evangelink Looks much better :-) But still a few nullable issues remain. I will open separate issues for those.
