### ISSUE TITLE
MSTest 3.0.0 is broken when targeting .NET Framework 4.8

### ISSUE THREAD

**Issue by avivanoff** [microsoft/testfx#1437]
## Steps To Reproduce

1. Create UnitTest project in Visual Studio 2022.
2. Make sure target framework is .NET Framework 4.8.
3. Build and execute unit tests.

## Expected behavior
Tests execute.

## Actual behavior
Tests do not execute.

## Additional context
See attached sample project [TestProject1.zip](https://github.com/microsoft/testfx/files/10172832/TestProject1.zip).

Tests output:
```
Log level is set to Informational (Default).
Connected to test environment '< Local Windows Environment >'
Source code repository not available. Some features may not work as expected.
Test data store opened in 0.038 sec.
Downloaded solution cache containers in 0.112 sec.
Loaded 0 test records from 0 solution cache containers in 0.279 sec.
========== Starting test discovery ==========
========== Test discovery finished: 1 Tests found in 3.6 sec ==========
Test data store opened in 0.016 sec.
========== Starting test discovery ==========
========== Test discovery skipped: All test containers are up to date ==========
Building Test Projects
========== Starting test run ==========
An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Stack trace:
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.TestDeployment.GetDeploymentInformation(String source)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.ExecuteTestsInSource(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, String source, Boolean isDeploymentDone)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.ExecuteTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, Boolean isDeploymentDone)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunCancellationToken runCancellationToken)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithTests.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUri, RunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.<>c__DisplayClass46_0.<RunTestInternalWithExecutors>b__0()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.<>c__DisplayClass0_0.<Run>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.Run(Action action, PlatformApartmentState apartmentState, Boolean waitForCompletion)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.TryToRunInStaThread(Action action, Boolean waitForCompletion)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)

========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in 217 ms ==========

```

[AB#1696392](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1696392)

**Comment by Evangelink** [comment]
Hi @avivanoff,

Thanks for the bug report. I can reproduce the issue in VS as well. Could you confirm that running `dotnet test` in the folder works for you (it does for me with your sample project).

**Comment by Evangelink** [comment]
Hey there. I have a fix on-going but in the meantime you can disable AppDomain (if that's ok for your tests) and it will workaround the issue. Here is a full example of a runsettings to use to disable appdomains:

```xml
<RunSettings>   
	<RunConfiguration>  
		<DisableAppDomain>True</DisableAppDomain>   
	</RunConfiguration>  
</RunSettings>
```

**Comment by dgasaway** [comment]
I'm not the reporter, but I can say that the runsettings workaround did work for my project.

**Comment by wangyoutian** [comment]
Same issue when targeting FrameWork 4.8.1;  I reported my issue through Visual Studio Help menu, where there is a report-issue link, and the moderator directs me here. 

Currently I downgraded the version from 3.0.0, to 2.2.7 to work around this;

I have seen this has been fixed, and I will try the fixed version later.

**Comment by Evangelink** [comment]
Hi @wangyoutian,

We haven't yet published the v3.0.1 as we are handling a few more requests we had but the fix is on its way.

**Comment by arvindshmicrosoft** [comment]
> We haven't yet published the v3.0.1 as we are handling a few more requests we had but the fix is on its way.

@Evangelink any ETA for 3.0.1? No pressure from my side, just curious when to check back.

**Comment by Evangelink** [comment]
Hi @arvindshmicrosoft, we are testing the version internally at the moment. I hope to be able to release this week.

**Comment by jrmoreno1** [comment]
In case it makes a difference, I didn't even have a .runsettings file when I first encountered this problem, and adding one (with the contents above) didn't fix the problem.

**Comment by Evangelink** [comment]
Hey all, we just released MSTest 3.0.1.

**Comment by avivanoff** [comment]
@Evangelink, 3.0.1 is still broken. I am trying to make a sample project,  it so far it looks like it happens when unit test assembly depends on one of our assemblies that have P/Invoke. This is the error:

```
An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not load file or assembly 'Microsoft.TestPlatform.CoreUtilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Stack trace:
 
Server stack trace:
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment.AssemblyLoadWorker.GetFullPathToDependentAssemblies(String assemblyPath, IList`1& warnings)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.PrivateProcessMessage(RuntimeMethodHandle md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
 
Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment.AssemblyLoadWorker.GetFullPathToDependentAssemblies(String assemblyPath, IList`1& warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.AssemblyUtility.GetFullPathToDependentAssemblies(String assemblyPath, String configFile, IList`1& warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.DeploymentUtility.AddDependencies(String testSource, String configFile, IList`1 deploymentItems, IList`1 warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.DeploymentUtility.AddDependenciesOfDeploymentItem(String deploymentItemFile, IList`1 filesToDeploy, IList`1 warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.DeploymentUtilityBase.Deploy(IList`1 deploymentItems, String testSource, String deploymentDirectory, String resultsDirectory)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.DeploymentUtilityBase.Deploy(String source, IRunContext runContext, ITestExecutionRecorder testExecutionRecorder, IList`1 deploymentItems, TestRunDirectories runDirectories)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.TestDeployment.Deploy(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunCancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.<>c__DisplayClass46_0.<RunTestInternalWithExecutors>b__0()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.<>c__DisplayClass0_0.<Run>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.Run(Action action, PlatformApartmentState apartmentState, Boolean waitForCompletion)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.TryToRunInStaThread(Action action, Boolean waitForCompletion)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)
```

**Comment by Evangelink** [comment]
@avivanoff Are you using the same repro project? I just tried again and I don't have the issue. Could you try to clean and rebuild your project?

**Comment by ms6073** [comment]
I see the same error with our automation framework built on ..Net 6 but interestingly, am also seeing the following warning when compiling the project which seems relevant as 17.4.1 is the latest version of Microsoft.NET.Test.Sdk and Microsoft.TestPlatform.TestHost.

Warning	NU1608	Detected package version outside of dependency constraint: MSTest 3.0.1 requires Microsoft.NET.Test.Sdk (= 17.4.0) but version Microsoft.NET.Test.Sdk 17.4.1 was resolved.

**Comment by avivanoff** [comment]
@Evangelink, add a DeploymentItem.

**Comment by avivanoff** [comment]
Updated sample project. Build and execute tests by running the following comment from the solution folder:

`"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" TestProject1\bin\Debug\net48\TestProject1.dll /Settings:"TestProject1\local.runsettings" /TestAdapterPath:TestProject1\bin\Debug\net48`

[TestProject1.zip](https://github.com/microsoft/testfx/files/10272264/TestProject1.zip)

**Comment by ms6073** [comment]
While our solution does not actually need it, when I installed MSTest 3.0.1, cleaned, and compiled the solution, I get the following warning which I find relevant as we are using the latest version (17.4.1) of Microsoft.NET.Test.Sdk as well as several other Nuget references:

Warning	NU1608	Detected package version outside of dependency constraint: MSTest 3.0.1 requires Microsoft.NET.Test.Sdk (= 17.4.0) but version Microsoft.NET.Test.Sdk 17.4.1 was resolved.	Automation.Framework	C:\Repos\Automation-Framework\Automation.Framework\Automation.Framework.csproj	1

**Comment by avivanoff** [comment]
Filed a new bug #1493.

**Comment by ms6073** [comment]
> @Evangelink, 3.0.1 is still broken.

I am seeing a different error

> Building Test Projects
========== Starting test run ==========
System.InvalidOperationException: TestsForOrigin: Unknown TestCaseRecord.Origin value Unknown
   at Microsoft.VisualStudio.TestStorage.MergedTestGroup.TestsForOrigin(TestCaseOrigin origin)
   at Microsoft.VisualStudio.TestStorage.MergedTestGroup.MarkAsStale()
   at Microsoft.VisualStudio.TestStorage.MergedTestIndex.MarkAsStale(TestCaseOriginKind originKind)
   at Microsoft.VisualStudio.TestStorage.TestStoreIndexSet.MarkTestsAsStale(TestCaseOriginKind originKind)
   at Microsoft.VisualStudio.TestStorage.TestStore.MarkTestsAsStale(TestCaseOriginKind originKind)
   at Microsoft.VisualStudio.TestWindow.Host.TestRunSession.StartTestRun(IEnumerable`1 containers, IEnumerable`1 requestedTestCasesToRun, Boolean isHotReloadRun)
   at Microsoft.VisualStudio.TestWindow.Host.VsTestRunSession.StartTestRun(IEnumerable`1 containers, IEnumerable`1 requestedTestCasesToRun, Boolean isHotReloadedRun, Int32 totalIterations)
   at Microsoft.VisualStudio.TestWindow.Host.VsTestRunSession.StartTestRun(ICollection`1 requests, Int32 totalIterations)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.CallInternalWithLogging(IInternalLogger log, Action action, Boolean shouldThrow)
System.InvalidOperationException: TestsForOrigin: Unknown TestCaseRecord.Origin value Unknown
   at Microsoft.VisualStudio.TestStorage.MergedTestGroup.TestsForOrigin(TestCaseOrigin origin)
   at Microsoft.VisualStudio.TestStorage.MergedTestGroup.MarkAsNotRunningAndNotPending()
   at Microsoft.VisualStudio.TestStorage.MergedTestIndex.MarkAsNotRunningAndNotPending(TestCaseOriginKind originKind)
   at Microsoft.VisualStudio.TestStorage.TestStoreIndexSet.MarkTestsAsNotRunningAndNotPending(TestCaseOriginKind originKind)
   at Microsoft.VisualStudio.TestStorage.TestStore.MarkTestsAsNotRunningAndNotPending(TestCaseOriginKind originKind)
   at Microsoft.VisualStudio.TestWindow.Host.VsTestRunSession.EndTestRun()
   at Microsoft.VisualStudio.TestWindow.Host.VsTestRunSession.OnTestRunCompleted()
   at Microsoft.VisualStudio.TestWindow.Utilities.EventPumpExtensions.<>c__DisplayClass0_0.<EnqueueAsync>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Host.TestPlatformProvider.<RunTestsAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Host.TestPlatformProvider.<RunTestsAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()

**Comment by Evangelink** [comment]
> While our solution does not actually need it, when I installed MSTest 3.0.1, cleaned, and compiled the solution, I get the following warning which I find relevant as we are using the latest version (17.4.1) of Microsoft.NET.Test.Sdk as well as several other Nuget references:
> 
> Warning NU1608 Detected package version outside of dependency constraint: MSTest 3.0.1 requires Microsoft.NET.Test.Sdk (= 17.4.0) but version Microsoft.NET.Test.Sdk 17.4.1 was resolved. Automation.Framework C:\Repos\Automation-Framework\Automation.Framework\Automation.Framework.csproj 1

This should not be causing any issue as `17.4.1` fixes don't impact the contract between test framework and test platform.

**Comment by ms6073** [comment]
> @Evangelink, updated sample project. Build and execute tests by running the following command from the solution folder:
> 
> `"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" TestProject1\bin\Debug\net48\TestProject1.dll /Settings:"TestProject1\local.runsettings" /TestAdapterPath:TestProject1\bin\Debug\net48`
> 
> [TestProject1.zip](https://github.com/microsoft/testfx/files/10272264/TestProject1.zip)

Although I did change the local.runsettings file after I downloaded the solution, I was able to run it as a net48, net6, and net7 project without any issues. 

`<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <RunConfiguration>
    <ResultsDirectory>.\TestResults</ResultsDirectory>
    <TreatNoTestsAsError>true</TreatNoTestsAsError>
  </RunConfiguration>
  <TestRunParameters>
  </TestRunParameters>
</RunSettings>`
