### ISSUE TITLE
Adding Init/Cleanup timeouts change the threading of these methods

### ISSUE THREAD

**Issue by drognanar** [microsoft/testfx#2700]
If you have a [TestInitialize] method, previously it would run on an STA thread. Now it runs on an MTA thread.
This seems related to the timeout change, as it runs the initializer finalizer on a separate Task, thus breaking the tests that expected an STA thread.

Even when using the new runsetting `<ExecutionThreadApartmentState>STA</ExecutionThreadApartmentState>`, the thread of the initialized method is still MTA.

**Comment by MarcoRossignoli** [comment]
It should be fixed in https://github.com/microsoft/testfx/pull/2682

**Comment by Evangelink** [comment]
Good point! I only tested the test method, I think this is still buggy because we added the `Task.Run` and I don't recall having fixed that part.

**Comment by jlaanstra** [comment]
I'm having issues as well after updating to 3.3.1 where the thread for the AssemblyInitialize function is no longer the same as the one that executes the tests.

**Comment by Evangelink** [comment]
Alright so I guess I'll bump prio on this one and backport it to 3.3.2.
