### ISSUE TITLE
Possibly missing unit test of duplicate method names

### ISSUE THREAD

**Issue by jn-foreflight** [microsoft/testfx#3970]
With v3.6.0 I found that one of my parameterized tests started to fail.
The problem turned out to be that the test class had two parameterized test with different method signatures but identical method names.
It seemed that for some versions the test adapter had recognized them as the same method and only run one of them.
I had a look at the [release notes](https://github.com/microsoft/testfx/blob/main/docs/Changelog.md#360---2024-09-11) for v3.6.0 but couldn't see which PR fixed this scenario.
A blind guess is that this was fixed as a bonus effect of #3366 but it doesn't seem it explicitly tests duplicate method names.

So what I'm suggesting is adding tests to guard against this scenario breaking again.

Given the test code and project below I tested with the following combos of TestAdapter+TestFramework

* v2.2.3: ❌ found two tests, but both succeeded (running the same test twice?)
* v2.2.4: ❌ found a single test which passed
* v3.5.2: ❌ found a single test which passed
* v3.6.0: ✔ found two tests, one failing

```cs
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestProject1;

[TestClass]
public class UnitTest1
{
    [DataTestMethod]
    [DataRow(1000.0)]
    public void Foo(double x)
    {
    }

    [DataTestMethod]
    [DataRow(10000, 1000.0)]
    public void Foo(double x, double y)
    {
        Assert.Fail();
    }
}
```

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.0" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.0" />
  </ItemGroup>

</Project>
```

**Comment by Evangelink** [comment]
Hi @jn-foreflight,

It got fixed here `Feat: add support for overloaded parameterized tests` #3298. I marked it as feature request more than bug although both were making sense because I couldn't find any doc saying this was supported and found couple of related issues dating from super old versions.

Are you only looking at what fixed the issue or is there any issue with that?

**Comment by jn-foreflight** [comment]
Thanks, this perfectly answers my question.

I guess I only looked through the "fixed" section... 🙃
I was looking for what fixed this issue for me to see that this wasn't resolved by coincidence to confirm that the necessary tests where added to avoid regressing this.
