### ISSUE TITLE
DataRow display name in test context support

### ISSUE THREAD

**Issue by aydjay** [microsoft/testfx#4127]
## Summary

I have a test like this:

```c#
[TestClass]
public class TestClass
{
    public TestContext TestContext { get; set; }

    [DataTestMethod]
    [DataRow(2, 4, DisplayName = "Two squared")]
    [DataRow(4, 16, DisplayName = "Four Squared")]
    public void Square(int square, int result)
    {
        Math.Pow(square, 2).Should().Be(result);

        TestContext.TestName.Should().NotBe("Square");
    }
}
```

I consume the display name in my unit test run and I'm excpecting eith "Two squared" or "Four Squared". I'm getting "Square", which is the name of the DataTestMethod but not the DisplayName of the Data test

## Background and Motivation

I'm using a piece of string data in my unit test. I want to use that piece of data as my display name and I don't want to duplicate the entry.

## Proposed Feature

Add a property on the TestContext that gives the display name of the DataRow if it's a data driven test.

**Comment by Evangelink** [comment]
Hi @aydjay,

Which version of MSTest are you using? We have fixed similar issue recently.

**Comment by aydjay** [comment]
MsTest.TestAdapter: 3.1.1
MsTest.TestFramework: 3.1.1
Microsoft.NET.Test.Sdk: 17.10.0

I appreciate this isn't the latest version so I have updated to the latest version 3.6.3 and the issue is still happening.

It does look like: 
https://github.com/microsoft/testfx/commit/9d65550bdbc1c39f564c201792e5af0a88582cc2

will fix the issue.
